apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-baseline-nvidia-gpu-vllm-decode
spec:
  template:
    spec:
      containers:
        - name: modelserver
          env:
            - name: HF_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: matrixhub-hf-endpoint
                  key: HF_ENDPOINT
